apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - services.yaml
  - ingress.yaml

images:
  - name: ghcr.io/Benjakunee17/my-ui
    newName: ghcr.io/Benjakunee17/my-ui
    newTag: latest