name: Bump GitOps DEV

on:
  workflow_run:
    workflows: ["Build Image (DEV)"]
    types:
      - completed

permissions:
  contents: write

env:
  DEV_KUSTOMIZE: gitops/apps/my-ui/overlays/dev/kustomization.yaml

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get image tag from triggering SHA
        run: |
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update DEV newTag
        run: |
          sed -i "s/^\s*newTag:\s*.*/    newTag: ${TAG}/" "${DEV_KUSTOMIZE}"

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "${DEV_KUSTOMIZE}"
          git commit -m "dev: bump my-ui image to ${TAG}"
          git push